service: fq-notifier

provider:
  name: aws
  runtime: nodejs8.10
  stage: main
  region: us-east-1

package:
  exclude:
    - .eslintrc.json
    - package-lock.json
    - README.md

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: fq-notify
          method: post
